# Generated by Django 4.0.2 on 2022-02-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellio',
            new_name='apellido',
        ),
    ]
